<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MyProjects.aspx.cs" Inherits="PLWebKunden.MyProjects" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>MyProjects</title>
</head>
<body>
    <form id="formMyProjects" runat="server">
    <div>
    
        <asp:Button ID="btnMyProjectsMyTasks" runat="server" Text="MyTasks" OnClick="btnMyProjectsMyTasks_Click" />
        <asp:Button ID="btnMyProjectsUser" runat="server" Text="User" OnClick="btnMyProjectsUser_Click" />
        <asp:Button ID="btnMyProjectsLogout" runat="server" Text="Logout" OnClick="btnMyProjectsLogout_Click" />
    
    </div>
        <h2>MyProjects&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnMyProjectsAddProject" runat="server" Text="+ Add" OnClick="btnMyProjectsAddProject_Click" />
        </h2>
        <asp:GridView ID="MyProjectsView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="MyProjectsViewData">
            <Columns>
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="MyProjectsViewData" runat="server" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=C:\Users\Michael\Desktop\PM\DB\PM_DB.mdf;Integrated Security=True;Connect Timeout=30" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [Name] FROM [Project]"></asp:SqlDataSource>
    </form>
    </body>
</html>
