<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Tasks.aspx.cs" Inherits="PLWebKunden.Tasks" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Tasks</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:Button ID="btnTasksMyProjects" runat="server" Text="MyProjects" OnClick="btnTasksMyProjects_Click" />
        <asp:Button ID="btnTasksMyTasks" runat="server" Text="MyTasks" OnClick="btnTasksMyTasks_Click" />
        <asp:Button ID="btnTasksUser" runat="server" Text="User" OnClick="btnTasksUser_Click" />
        <asp:Button ID="btnTasksLogout" runat="server" Text="Logout" OnClick="btnTasksLogout_Click" />
    
    </div>
        <h2>
            <asp:Label ID="lblTasksWorkPackagename" runat="server" Text="Label"></asp:Label>
&nbsp;- Tasks&nbsp;&nbsp;&nbsp; <asp:Button ID="btnTasksAddTask" runat="server" Text="+ Add" OnClick="btnTasksAddTask_Click" />
        </h2>
        <asp:GridView ID="TasksView" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnRowEditing="TasksView_RowEditing" OnSelectedIndexChanged="TasksView_SelectedIndexChanged" OnRowDeleting="TasksView_RowDeleting">
        </asp:GridView>
    </form>
    </body>
</html>
