<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Tasks.aspx.cs" Inherits="PLWebKunden.WorkPackages" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Tasks</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:Button ID="btnTasksMyProjects" runat="server" Text="MyProjects" />
        <asp:Button ID="btnTasksMyTasks" runat="server" Text="MyTasks" />
        <asp:Button ID="btnTasksUser" runat="server" Text="User" />
        <asp:Button ID="btnTasksLogout" runat="server" Text="Logout" />
    
    </div>
        <h2>Tasks&nbsp;&nbsp;&nbsp; <asp:Button ID="btnTasksAddProject" runat="server" Text="+ Add" />
        </h2>
        <asp:GridView ID="TasksView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        </asp:GridView>
    </form>
    </body>
</html>
